version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - redisearch
    environment:
      SPRING_REDIS_HOST: redisearch
      STOMP_PORT: 80

  redisearch:
    image: redislabs/redisearch:latest
    restart: always
    ports:
      - "6379:6379"
